
[language-server.dprint]
command = "dprint"
args = ["lsp"]

[language-server.ltex-ls]
command = "ltex-ls"

[language-server.helm-ls]
command = "helm_ls"

[language-server.taplo.config]
config = {}

[language-server.gopls.config]
gofumpt = true

[language-server.yaml-language-server.config]
yaml = { keyOrdering = false }

[[language]]
name = "scala"
language-servers = ["metals"]
auto-format = true

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]
formatter = { command = "rufo", args = ["--simple-exit"] }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls"]
auto-format = true

[[language]]
name = "elixir"
language-servers = ["elixir-ls"]
auto-format = true

[[language]]
name = "heex"
language-servers = ["elixir-ls"]
auto-format = true

[[language]]
name = "eex"
file-types = [
  "eex",
  "erb",
  { glob = "*.html.erb" },
  { glob = "*.xml.erb" },
  { glob = "*.js.erb" },
  { glob = "*.css.erb" },
  { glob = "*.json.erb" },
  { glob = "*.yml.erb" },
  { glob = "*.yaml.erb" },
]
auto-format = false

[[language]]
name = "gotmpl"
file-types = [
  "gotmpl",
  "tpl",
  "tmpl",
  { glob = "**/templates/**/*.tpl" },
  { glob = "**/templates/**/*.yaml" },
  { glob = "**/templates/**/*.yml" },
]
roots = ["Chart.yaml", "go.mod", ".git"]
language-servers = ["gopls", "helm-ls"]
auto-format = false

[[language]]
name = "json"
formatter = { command = "sh", args = ["-c", "dprint fmt --stdin %{buffer_name} --config $HOME/.config/helix/dprint.json"] }
language-servers = [{ name = "dprint", only-features = ["format"] }]
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "sh", args = ["-c", "dprint fmt --stdin %{buffer_name} --config $HOME/.config/helix/dprint.json"] }
language-servers = [
  { name = "marksman", except-features = ["format"] },
  { name = "dprint", only-features = ["format"] },
]
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "yq", args = ["-P", "."] }
language-servers = [
  { name = "yaml-language-server", except-features = ["format"] },
]
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["-i", "2", "-ci"] }
auto-format = true

[[language]]
name = "make"
file-types = ["mk", { glob = "Makefile" }, { glob = "GNUmakefile" }, { glob = "*.mk" }]
auto-format = false

[[language]]
name = "hocon"
auto-format = false

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
auto-format = true

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
language-servers = ["lua-language-server"]
auto-format = true

[[language]]
name = "mermaid"
auto-format = false
