inherits = "catppuccin_mocha"

"ui.background" = { bg = "#000000" }
"ui.gutter" = { bg = "#000000" }
"ui.gutter.selected" = { bg = "#000000" }
"ui.linenr" = { bg = "#000000" }
"ui.linenr.selected" = { fg = "#89b4fa", bg = "#000000" }
"ui.statusline" = { bg = "#1e1e2e", fg = "#cdd6f4" }
"ui.statusline.inactive" = { bg = "#181825", fg = "#a6adc8" }
"ui.statusline.normal" = { fg = "#89b4fa", bg = "#1e1e2e", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "#a6e3a1", bg = "#1e1e2e", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "#cba6f7", bg = "#1e1e2e", modifiers = ["bold"] }
"ui.statusline.separator" = { fg = "#585b70", bg = "#1e1e2e" }
"ui.window" = { fg = "#45475a" }
"ui.popup" = { bg = "#000000" }
"ui.popup.info" = { bg = "#000000", fg = "#a6adc8" }
"ui.menu" = { bg = "#000000" }
"ui.menu.selected" = { bg = "#313244" }
"ui.help" = { bg = "#000000" }
"ui.selection" = { bg = "#313244" }
"ui.selection.primary" = { bg = "#45475a" }
